import { spawnSync } from "node:child_process";
import type { Finding } from "./schemas.ts";

export function slugify(text: string): string {
  return text
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");
}

export function issueTitle(controlRef: string, findingTitle: string): string {
  return `[SOC2] ${controlRef}: ${findingTitle}`;
}

export function issueBody(finding: Finding): string {
  const fileLine = finding.file_path ? `\n**File:** \`${finding.file_path}\`` : "";
  return `## SOC2 Finding: ${finding.soc2_reference}

**Severity:** ${finding.severity}
**Category:** ${finding.category}${fileLine}

### Description
${finding.description}

### Recommendation
${finding.recommendation}

---
*Generated by [opper-soc2-audit-action](https://github.com/opper-ai/opper-soc2-audit-action)*`;
}

function ghJson<T>(args: string[]): T | null {
  const result = spawnSync("gh", args, { encoding: "utf8", timeout: 30_000 });
  if (result.error || result.status !== 0) return null;
  try { return JSON.parse(result.stdout.trim()); } catch { return null; }
}

function ghRun(args: string[]): boolean {
  const result = spawnSync("gh", args, { encoding: "utf8", timeout: 30_000 });
  return !result.error && result.status === 0;
}

function ensureLabel(owner: string, repo: string, label: string, color: string): void {
  const exists = ghJson<{ name: string }[]>(["label", "list", "--repo", `${owner}/${repo}`, "--json", "name"]);
  if (Array.isArray(exists) && exists.some((l) => l.name === label)) return;
  ghRun(["label", "create", label, "--repo", `${owner}/${repo}`, "--color", color, "--force"]);
}

type ExistingIssue = { number: number; title: string };

function findExistingIssue(owner: string, repo: string, title: string): number | null {
  const issues = ghJson<ExistingIssue[]>([
    "issue", "list",
    "--repo", `${owner}/${repo}`,
    "--state", "open",
    "--search", title,
    "--json", "number,title",
    "--limit", "10",
  ]);
  if (!issues) return null;
  const match = issues.find((i) => i.title === title);
  return match ? match.number : null;
}

function commentOnIssue(owner: string, repo: string, issueNumber: number, finding: Finding): void {
  const body = `## Updated finding from latest SOC2 audit\n\n${issueBody(finding)}`;
  ghRun(["issue", "comment", String(issueNumber), "--repo", `${owner}/${repo}`, "--body", body]);
}

function createIssue(owner: string, repo: string, finding: Finding, controlRef: string): number | null {
  ensureLabel(owner, repo, "soc2-audit", "0075ca");
  ensureLabel(owner, repo, `severity:${finding.severity}`, finding.severity === "critical" ? "d73a4a" : "e4e669");

  const result = spawnSync(
    "gh",
    [
      "issue", "create",
      "--repo", `${owner}/${repo}`,
      "--title", issueTitle(controlRef, finding.title),
      "--body", issueBody(finding),
      "--label", "soc2-audit",
      "--label", `severity:${finding.severity}`,
    ],
    { encoding: "utf8", timeout: 30_000 },
  );
  if (result.error || result.status !== 0) {
    console.warn(`  [issues] Failed to create issue: ${(result.stderr ?? "").trim()}`);
    return null;
  }
  const url = result.stdout.trim();
  const match = url.match(/\/issues\/(\d+)$/);
  return match ? parseInt(match[1], 10) : null;
}

/** Create or update GitHub issues for critical/high findings. Returns map of finding index → issue number. */
export async function createOrUpdateIssues(
  owner: string,
  repo: string,
  findings: Finding[],
  controlRef: string,
): Promise<Map<number, number>> {
  const issueMap = new Map<number, number>();
  const actionable = findings.filter((f) => f.severity === "critical" || f.severity === "high");

  for (const [i, finding] of actionable.entries()) {
    const title = issueTitle(controlRef, finding.title);
    const existing = findExistingIssue(owner, repo, title);
    if (existing) {
      console.log(`  [issues] Commenting on existing issue #${existing}: ${finding.title}`);
      commentOnIssue(owner, repo, existing, finding);
      issueMap.set(i, existing);
    } else {
      console.log(`  [issues] Creating issue: ${finding.title}`);
      const num = createIssue(owner, repo, finding, controlRef);
      if (num) issueMap.set(i, num);
    }
  }
  return issueMap;
}
